### ISSUE TITLE
Maven Central publishing

### ISSUE THREAD

**Issue by augi** [avast/scala-hashes#8]
As [JCenter will shutdown on May 1st 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), we have to start publishing to Maven Central.

**Comment by sideeffffect** [comment]
If you make the decision to move over to sbt (it has easy publishing to Maven), I can help :+1: (But maybe it's easy to do with Gradle as well, I don't really know.)

**Comment by augi** [comment]
`2.3.1` published to Maven Central.
